### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by Fourteen98** [Fourteen98/officeverse-api#17]
- Created two empty repositories for the project
- Created the kanboard 
- Created the cards based on the requeirements
- Assigned cards to team members

Team members: 
@diegoyon 
@raminka13 
@jaferIdrees 
@Fourteen98 

> Link to [officeverse frontend](https://github.com/Fourteen98/officeverse-frontend)
> Link to [officeverse-api](https://github.com/Fourteen98/officeverse-api)

[link to kanboard](https://github.com/users/Fourteen98/projects/8/views/1)

Screenshot
![image](https://user-images.githubusercontent.com/44606356/203862531-d6b158e4-fcbe-4ef3-b11a-a30f6339c3d6.png)

**Comment by Meltrust** [comment]
Hi @Fourteen98,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- Cards are pointed and assigned in a fair way✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

### Your kanban board has one extra column

Based on the project requirements:

![image](https://user-images.githubusercontent.com/57421823/203863821-e3689d73-6f4a-4898-9ebc-6dd825c321e8.png)

Therefore:

- [x] Kindly only use the required columns and merge the todo tasks.

## Explanation

1. Adding an extra column for the tasks on both apps makes a lot of sense, however, we should stick to the requirements for now.  You will encounter lots of requirements in the industry that may not make complete sense to you, but those are _requirements_ and are _required_.

2. In the real software industry, we **never** do multiple tasks columns or even multiple kanban boards for a single project, even if it spans more than one app, or more than one repo.  

3. I hope this helps, and makes sense to you.



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi @Fourteen98,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!






### To highlight

- The required columns are now being used✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
